apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: juice-shop-reader
  namespace: juice-shop

rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]